site_name: DJBenson's HA Stuff
site_url: https://djbenson.github.io
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - navigation.top

