site_name: DJBenson's HA Stuff
site_url: https://djbenson.github.io
repo_url: djbenson/ha-stuff
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.highlight

plugins:
  - search
